language: python

python:
  - 3.5
  - 3.6

install: pip install -r requirements.txt

script:
  - pip install coverage coveralls
  - coverage run --source=bitex setup.py test

after_success: coveralls

after_failure: ./travis/force_deploy_on_nightly.sh

jobs:
  allow_failures:
  include:
    - stage: lint
      python: 3.6
      script:
        - pip install pylint
        - pylint --rcfile=pylint.rc bitex
    - stage: lint
      python: 3.6
      script:
        - pip install pydocstyle
        - pydocstyle bitex
    - stage: lint
      python: 3.6
      script:
        - pip install pycodestyle
        - pycodestyle --max-line-length=100 bitex
    - stage: compile
      python: 3.5
      script: python setup.py install
    - stage: deploy
      python: 3.5
      script: ./travis/deploy.sh

stages:
  - name: lint
    if: branch != nightly
  - compile
  - name: test
    if: branch != nightly
  - name: deploy
    if: tag IS present OR branch = nightly
